stages:
  - test 
  - build
  - deploy

build-job: 
  stage: build
  image: node
  script: 
    - echo "Hello $GITLAB_USER_LOGIN m ready to build your app"
    - npm i
    - npm run build
  artifacts: 
    paths: 
      - "dist/"

test-job: 
  stage: test
  image : node
  script: 
    - npm i
    - echo "Ready to run tests"
    - npm test

deploy-prod: 
  stage: deploy
  script: 
    - echo "Deploy $CI_COMMIT_BRANCH branch to target"
  environment: production